#!/bin/bash

# Diretórios relativos
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

clear
echo ""
echo "╔══════════════════════════════════════════════════════════════════════════════╗"
echo "║      🧪 AESC v1.0 | Ambiente de Execução de Simulações Científicas           ║"
echo "║              💻 Laboratório Pessoal de Computação Científica                 ║"
echo "║                Desenvolvido por Prof. Rafael Gabler Gontijo                  ║"
echo "╠══════════════════════════════════════════════════════════════════════════════╣"
echo "║          Ambiente de execução – SIMMSUS 🧲 | Ajuda e informações             ║"
echo "╚══════════════════════════════════════════════════════════════════════════════╝"
echo ""
echo "📘 Este ambiente foi especialmente preparado para a execução de simulações"
echo "    com o código open source *SIMMSUS*, voltado à modelagem de sistemas de"
echo "    partículas magnéticas sujeitas a forças de interação de longo alcance."
echo ""
echo "🌐 Estrutura geral esperada:"
echo "  - 📁 As simulações devem estar organizadas em pastas dentro de:"
echo "       ../simulacoes/simmsus/"
echo "  - 📄 Cada pasta deve conter ao menos um arquivo obrigatório:"
echo "       simconfig.dat  ← arquivo de configuração da simulação"
echo ""
echo "⚙️  Para executar uma simulação:"
echo "  1. Compile o código SIMMSUS"
echo "  2. Crie uma pasta em ../simulacoes/simmsus/nome_do_caso"
echo "  3. Inclua nessa pasta o arquivo simconfig.dat correspondente"
echo "  4. Execute a simulação por meio dos menus do AESC"
echo ""
echo "📂 Pasta de exemplo incluída no sistema:"
echo "  Nome:  field_oscil_brown_noshear_n500_vf05"
echo ""
echo "  🔬 Essa simulação está configurada para:"
echo "    - 100 realizações simultâneas"
echo "    - 500 partículas magnéticas"
echo "    - Fração volumétrica de 5%"
echo "    - Ambiente Browniano (inclui efeitos térmicos)"
echo "    - Ação de campo externo oscilatório"
echo "    - Sem cisalhamento ativado"
echo ""
echo "🧩 O nome da pasta reflete alguns parâmetros da simulação, seguindo o padrão:"
echo "     field_oscil_brown_noshear_n500_vf05"
echo "     └── campo oscilatório | browniano | sem cisalhamento | n = 500 | vf = 5%"
echo ""
echo "✏️  O arquivo 'simconfig.dat' pode ser editado manualmente para configurar:"
echo "    - Número de partículas, tempo total, delta t"
echo "    - Tipo de simulação (Browniana, com ou sem campo, com ou sem cisalha)"
echo "    - Parâmetros físicos do sistema, entre outras informações"
echo ""
echo "🔖 Sugestão:"
echo "    - Mantenha a lógica de nomeação das pastas para boa organização."
echo "    - Copie a pasta exemplo como base para novas simulações."
echo "    - Altere o simconfig.dat dentro de novas pastas conforme necessário."
echo ""
read -p "Pressione ENTER para retornar ao menu SIMMSUS..." 
bash "$SCRIPT_DIR/menu_simmsus.sh"
