#!/bin/sh
# Source tutprial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions  
#------------------------------------------------------------------------------

cp -r 0.orig/ 0/
runApplication blockMesh
runApplication setFields


#------------------------------------------------------------------------------

